// ═══════════════════════════════════════════════════════════════════════════════
// PlayoffSimController.js — Calendar-based playoff simulation
//
// Extracted from GameSimController.js (Phase 2A).
// Handles: simPlayoffDay, simPlayoffRound, simToChampionship, simUserPlayoffSeries,
//   bracket population, round tracking, completion detection, postseasonResults.
//
// Does NOT own watch-game state (_watchGame, _watchTimer, etc.) — that stays on
// GameSimController. watchPlayoffGame v2 also stays there since it sets up the
// watch infrastructure. _closeCalendarPlayoffWatch stays on GameSimController
// but delegates bracket updates here.
// ═══════════════════════════════════════════════════════════════════════════════

import { LeagueManager } from './LeagueManager.js';

export class PlayoffSimController {
    constructor(ctx) {
        this.ctx = ctx;
        // Reference to GameSimController — set after both are constructed
        this._gameSimController = null;
    }

    // ══════════════════════════════════════════════════════════════════════════
    // Utility: shared box-score stat mapper (was copy-pasted 5+ times)
    // ══════════════════════════════════════════════════════════════════════════

    static mapStats(stats) {
        return (stats || [])
            .filter(p => p.minutesPlayed > 0)
            .sort((a, b) => b.minutesPlayed - a.minutesPlayed)
            .map(p => ({
                name: p.playerName || p.name || 'Unknown', pos: p.position || '',
                min: p.minutesPlayed || 0, pts: p.points || 0,
                reb: p.rebounds || 0, ast: p.assists || 0,
                stl: p.steals || 0, blk: p.blocks || 0, to: p.turnovers || 0,
                pf: p.fouls || 0, starter: p.gamesStarted > 0,
                fgm: p.fieldGoalsMade || 0, fga: p.fieldGoalsAttempted || 0,
                tpm: p.threePointersMade || 0, tpa: p.threePointersAttempted || 0,
                ftm: p.freeThrowsMade || 0, fta: p.freeThrowsAttempted || 0, pm: p.plusMinus || 0
            }));
    }

    // ══════════════════════════════════════════════════════════════════════════
    // CALENDAR-BASED PLAYOFF SIMULATION
    // These methods work with playoffSchedule (generated by PlayoffEngine.generatePlayoffSchedule)
    // ══════════════════════════════════════════════════════════════════════════

    /**
     * Simulate all playoff games scheduled for the next game day.
     * This is the primary "Sim Game" action when user is in playoffs.
     */
    simPlayoffDay() {
        const { gameState, helpers, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        
        if (!schedule) {
            console.error('❌ simPlayoffDay: No playoff schedule found');
            return;
        }
        
        console.log('🏀 simPlayoffDay called, currentDate:', gameState.currentDate);
        
        // Find the next date with games to play (on or after current date)
        // Pass a date one day before current to include current date in search
        const searchFrom = engines.PlayoffEngine._addDays(gameState.currentDate, -1);
        const nextDate = engines.PlayoffEngine.getNextPlayoffGameDate(schedule, searchFrom);
        
        console.log('🏀 Next playoff game date:', nextDate);
        
        if (!nextDate) {
            console.log('✅ All playoff games complete');
            this._checkPlayoffsComplete();
            return;
        }
        
        // Get all necessary games on this date
        const gamesToday = engines.PlayoffEngine.getPlayoffGamesOnDate(schedule, nextDate);
        console.log(`🏀 Found ${gamesToday.length} games on ${nextDate}:`, gamesToday.map(g => g.id));
        
        if (gamesToday.length === 0) {
            console.log('⚠️ No necessary games found on', nextDate);
            // Try advancing to find next date with actual games
            gameState.currentDate = engines.PlayoffEngine._addDays(nextDate, 1);
            helpers.saveGameState();
            if (window._reactPlayoffHubRefresh) window._reactPlayoffHubRefresh();
            return;
        }
        
        for (const game of gamesToday) {
            this._simOneScheduledGame(game);
        }
        
        // Advance date
        gameState.currentDate = nextDate;
        
        // Populate next round matchups if any series completed
        this._updateBracketsAfterGames();
        
        helpers.saveGameState();
        
        // Refresh UI
        if (window._reactPlayoffHubRefresh) window._reactPlayoffHubRefresh();
        
        // Check if all playoffs are complete
        this._checkPlayoffsComplete();
    }

    /**
     * Simulate user's entire current series to completion.
     */
    simUserPlayoffSeries() {
        const { gameState, helpers, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        const userSeriesId = gameState.userSeriesId;
        
        if (!schedule || !userSeriesId) {
            console.error('❌ simUserPlayoffSeries: No schedule or user series');
            return;
        }
        
        const seriesGames = schedule.bySeries[userSeriesId] || [];
        const bestOf = seriesGames[0]?.bestOf || 7;
        const winsNeeded = Math.ceil(bestOf / 2);
        
        // Sim until series is decided
        let iterations = 0;
        while (iterations < 10) { // Safety limit
            iterations++;
            
            const state = engines.PlayoffEngine.getSeriesState(schedule, userSeriesId);
            if (state.complete) {
                console.log(`✅ User series complete: ${state.higherSeedWins}-${state.lowerSeedWins}`);
                break;
            }
            
            // Find next unplayed game in this series
            const nextGame = seriesGames.find(g => !g.played);
            if (!nextGame) break;
            
            this._simOneScheduledGame(nextGame);
            
            // Also sim other games on the same date
            const otherGames = engines.PlayoffEngine.getPlayoffGamesOnDate(schedule, nextGame.date)
                .filter(g => g.id !== nextGame.id);
            for (const g of otherGames) {
                this._simOneScheduledGame(g);
            }
            
            gameState.currentDate = nextGame.date;
        }
        
        this._updateBracketsAfterGames();
        
        // Update user's series ID for next round if they won
        this._updateUserSeriesForNextRound();
        
        helpers.saveGameState();
        if (window._reactPlayoffHubRefresh) window._reactPlayoffHubRefresh();
        this._checkPlayoffsComplete();
    }

    /**
     * Simulate all games in the current playoff round until it completes.
     */
    simPlayoffRound() {
        const { gameState, helpers, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        
        if (!schedule) {
            console.error('❌ simPlayoffRound: No playoff schedule found');
            return;
        }
        
        // Get user's tier
        const userTier = gameState.userTier || gameState.currentTier || 1;
        const tierPrefix = `t${userTier}-`;
        
        // Determine current round for USER'S TIER from earliest incomplete series
        const currentRound = this._getCurrentPlayoffRoundForTier(userTier);
        if (!currentRound) {
            console.log(`✅ All T${userTier} rounds complete`);
            this._checkPlayoffsComplete();
            return;
        }
        
        console.log(`🏀 Simulating T${userTier} playoff round: ${currentRound}`);
        
        // Find the latest date needed to complete this round
        const roundGames = schedule.games.filter(g => 
            g.seriesId?.startsWith(tierPrefix) && g.round === currentRound && !g.played
        );
        
        if (roundGames.length === 0) {
            console.log(`✅ Round ${currentRound} already complete`);
            this._updateBracketsAfterGames();
            this._updateUserSeriesForNextRound();
            helpers.saveGameState();
            if (window._reactPlayoffHubRefresh) window._reactPlayoffHubRefresh();
            return;
        }
        
        // Find the last date of games in this round
        const roundDates = [...new Set(roundGames.map(g => g.date))].sort();
        const lastRoundDate = roundDates[roundDates.length - 1];
        
        console.log(`📅 Simulating all games through ${lastRoundDate} to complete round`);
        
        // Sim ALL games (all tiers) up through that date
        let iterations = 0;
        let gamesSimmed = 0;
        while (iterations < 500) { // Safety limit
            iterations++;
            
            // Find next unplayed game date across all tiers
            const nextDate = engines.PlayoffEngine.getNextPlayoffGameDate(schedule, null);
            if (!nextDate) break;
            
            // Stop if we've passed the round's end date
            if (nextDate > lastRoundDate) {
                // But first check if the user's round is actually complete
                if (this._isRoundCompleteForTier(currentRound, userTier)) {
                    break;
                }
                // Round not complete but no more games on expected dates - might need more games
                // This can happen in Bo7 series that go to game 7
                const stillNeeded = schedule.games.filter(g => 
                    g.seriesId?.startsWith(tierPrefix) && g.round === currentRound && !g.played
                );
                if (stillNeeded.length === 0) break;
                // Update lastRoundDate to include newly necessary games
            }
            
            // Get all games on this date (all tiers)
            const gamesToday = engines.PlayoffEngine.getPlayoffGamesOnDate(schedule, nextDate)
                .filter(g => !g.played && !g.skipped);
            
            if (gamesToday.length === 0) {
                gameState.currentDate = nextDate;
                continue;
            }
            
            for (const game of gamesToday) {
                if (!game.played && !game.skipped) {
                    this._simOneScheduledGame(game);
                    gamesSimmed++;
                }
            }
            
            gameState.currentDate = nextDate;
            
            // Check if user's tier round is now complete
            if (this._isRoundCompleteForTier(currentRound, userTier)) {
                console.log(`✅ T${userTier} round ${currentRound} complete after ${gamesSimmed} games`);
                break;
            }
        }
        
        this._updateBracketsAfterGames();
        this._updateUserSeriesForNextRound();
        
        helpers.saveGameState();
        if (window._reactPlayoffHubRefresh) window._reactPlayoffHubRefresh();
        this._checkPlayoffsComplete();
    }

    /**
     * Fast-forward through all remaining playoff games.
     */
    simToChampionship() {
        const { gameState, helpers, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        
        if (!schedule) {
            console.error('❌ simToChampionship: No playoff schedule found');
            return;
        }
        
        console.log('🏆 Simulating all remaining playoff games...');
        
        let iterations = 0;
        let gamesSimmed = 0;
        while (iterations < 1000) { // Safety limit
            iterations++;
            
            const nextDate = engines.PlayoffEngine.getNextPlayoffGameDate(schedule, null);
            if (!nextDate) {
                console.log(`✅ All playoff games complete after ${gamesSimmed} games`);
                break;
            }
            
            const gamesToday = engines.PlayoffEngine.getPlayoffGamesOnDate(schedule, nextDate);
            if (gamesToday.length === 0) {
                // No necessary games on this date, skip it
                gameState.currentDate = engines.PlayoffEngine._addDays(nextDate, 1);
                continue;
            }
            
            for (const game of gamesToday) {
                this._simOneScheduledGame(game);
                gamesSimmed++;
            }
            
            gameState.currentDate = nextDate;
            this._updateBracketsAfterGames();
        }
        
        // Mark playoffs as complete
        if (gameState.playoffData) {
            gameState.playoffData.completed = true;
        }
        
        // Build postseasonResults for offseason flow compatibility
        this._buildPostseasonResults();
        
        // Mark playoffs as completed
        gameState.playoffData.completed = true;
        
        helpers.saveGameState();
        if (window._reactPlayoffHubRefresh) window._reactPlayoffHubRefresh();
        
        // Don't immediately trigger offseason - let user view results first
        // The PlayoffHub will show "View Results" button which opens PlayoffEndModal
        // When user clicks "Begin Offseason" in that modal, it will trigger offseason
        console.log('🏁 Playoffs complete - View Results button will appear in PlayoffHub');
    }

    // ─── Helper: Simulate one scheduled playoff game ─────────────────────────────

    _simOneScheduledGame(game) {
        const { gameState, helpers, engines } = this.ctx;
        
        if (game.played) return; // Already played
        if (game.placeholder && !game.homeTeamId) return; // Teams not determined
        
        // Check if game is still necessary (series not decided)
        if (!engines.PlayoffEngine.isGameNecessary(gameState.playoffSchedule, game.id)) {
            game.played = true; // Mark as skipped
            game.skipped = true;
            return;
        }
        
        // Get team objects
        const allTeams = [
            ...(gameState.tier1Teams || []),
            ...(gameState.tier2Teams || []),
            ...(gameState.tier3Teams || [])
        ];
        const homeTeam = allTeams.find(t => t.id === game.homeTeamId);
        const awayTeam = allTeams.find(t => t.id === game.awayTeamId);
        
        if (!homeTeam || !awayTeam) {
            console.warn(`⚠️ Could not find teams for game ${game.id}`);
            return;
        }
        
        // Simulate the game
        const result = helpers.getSimulationController().simulatePlayoffGame(homeTeam, awayTeam);
        
        // Record result
        game.played = true;
        game.result = {
            homeScore: result.homeScore,
            awayScore: result.awayScore,
            winner: result.winner,
            loser: result.loser,
            overtime: result.overtime || false
        };
        
        // Store box score if this is a user's series game
        const userTeamId = gameState.userTeamId;
        const isUserGame = game.homeTeamId === userTeamId || game.awayTeamId === userTeamId;
        if (isUserGame && result.homePlayerStats && result.awayPlayerStats) {
            game.boxScore = {
                home: { city: homeTeam.city || '', name: homeTeam.name, score: result.homeScore, players: PlayoffSimController.mapStats(result.homePlayerStats) },
                away: { city: awayTeam.city || '', name: awayTeam.name, score: result.awayScore, players: PlayoffSimController.mapStats(result.awayPlayerStats) },
                quarterScores: result.quarterScores || null,
                winProbHistory: result.winProbHistory || null,
                preGameProb: result.preGameProb || null
            };
        }
        
        console.log(`  ${game.round} G${game.gameNumber}: ${homeTeam.name} ${result.homeScore} - ${result.awayScore} ${awayTeam.name}`);
    }

    // ─── Helper: Update brackets after games complete ────────────────────────────

    _updateBracketsAfterGames() {
        const { gameState, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        const playoffData = gameState.playoffData;
        
        if (!schedule || !playoffData) return;
        
        // Check each series for completion and populate next round
        for (const [seriesId, games] of Object.entries(schedule.bySeries)) {
            const state = engines.PlayoffEngine.getSeriesState(schedule, seriesId);
            
            if (state.complete && state.winner) {
                // Find the next series this winner advances to
                const nextSeriesId = this._getNextSeriesId(seriesId);
                if (nextSeriesId && schedule.bySeries[nextSeriesId]) {
                    this._populateSeriesWithTeam(nextSeriesId, state.winner, seriesId);
                }
            }
        }
        
        // Handle T2 division → national tournament transition
        this._checkT2NationalTournamentSeeding();
        
        // Handle T3 metro → regional → sweet16 transitions
        this._checkT3TournamentSeeding();
        
        // Handle 3rd place games (losers of semis)
        this._checkThirdPlaceGames();
    }
    
    /**
     * Check if all T2 division finals are complete and seed national tournament.
     */
    _checkT2NationalTournamentSeeding() {
        const { gameState, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        
        // Find all division final series
        const divFinalSeries = Object.keys(schedule.bySeries).filter(id => 
            id.startsWith('t2-div-') && id.endsWith('-final')
        );
        
        console.log(`📊 T2 Division Finals check: ${divFinalSeries.length} series`);
        
        // Check if all are complete
        const divWinners = [];
        const divRunnersUp = [];
        for (const seriesId of divFinalSeries) {
            const state = engines.PlayoffEngine.getSeriesState(schedule, seriesId);
            if (!state.complete) {
                console.log(`   ${seriesId}: incomplete`);
                return; // Not all complete yet
            }
            if (state.winner) divWinners.push(state.winner);
            if (state.loser) divRunnersUp.push(state.loser);
        }
        
        console.log(`📊 T2 Division Finals complete: ${divWinners.length} winners`);
        
        // Check if national tournament is already seeded
        const natR1Series = Object.keys(schedule.bySeries).filter(id => 
            id.startsWith('t2-nat-r1-')
        ).sort();
        
        if (natR1Series.length > 0) {
            const firstNatGame = schedule.bySeries[natR1Series[0]]?.[0];
            if (firstNatGame?.homeTeamId) {
                console.log('📊 T2 National already seeded');
                return; // Already seeded
            }
        }
        
        // All division finals complete - seed national tournament round 1
        // With 11 divisions, we have 11 winners. Take top 8 by regular season record
        // (or we could include some runners-up for a 16-team field)
        
        // For now: top 11 division winners, sorted by record, fill 8 series (16 spots)
        // Add top 5 runners-up to make 16 teams
        const allQualifiers = [...divWinners];
        
        // Sort by regular season record
        allQualifiers.sort((a, b) => (b.wins - a.wins) || (b.pointDiff - a.pointDiff));
        
        // If we have fewer than 16 teams, add runners-up
        if (allQualifiers.length < 16 && divRunnersUp.length > 0) {
            divRunnersUp.sort((a, b) => (b.wins - a.wins) || (b.pointDiff - a.pointDiff));
            const needed = 16 - allQualifiers.length;
            allQualifiers.push(...divRunnersUp.slice(0, needed));
            allQualifiers.sort((a, b) => (b.wins - a.wins) || (b.pointDiff - a.pointDiff));
        }
        
        console.log(`📊 T2 National qualifiers: ${allQualifiers.length} teams`);
        
        // Seed 1v16, 2v15, 3v14, etc.
        for (let i = 0; i < Math.min(8, natR1Series.length); i++) {
            const highSeedIdx = i;
            const lowSeedIdx = allQualifiers.length - 1 - i;
            
            if (highSeedIdx < allQualifiers.length && lowSeedIdx >= 0 && lowSeedIdx < allQualifiers.length && highSeedIdx !== lowSeedIdx) {
                const highSeed = allQualifiers[highSeedIdx];
                const lowSeed = allQualifiers[lowSeedIdx];
                if (highSeed && lowSeed) {
                    this._populateSeriesWithTeams(natR1Series[i], highSeed, lowSeed);
                }
            }
        }
        
        // Update user's series ID if they're in the national tournament
        const userTeamId = gameState.userTeamId;
        if (userTeamId) {
            for (let i = 0; i < natR1Series.length; i++) {
                const games = schedule.bySeries[natR1Series[i]];
                if (games?.[0] && (games[0].homeTeamId === userTeamId || games[0].awayTeamId === userTeamId)) {
                    gameState.userSeriesId = natR1Series[i];
                    console.log(`🎯 User seeded in T2 National R1: ${natR1Series[i]}`);
                    break;
                }
            }
        }
    }
    
    /**
     * Check T3 tournament seeding (metro → regional → sweet16 → qf → sf → finals).
     */
    _checkT3TournamentSeeding() {
        const { gameState, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        
        if (!schedule?.bySeries) return;
        
        // T3 Structure:
        // Stage 1: Metro Finals (24 series) - t3-metro-{divId}
        // Stage 2: Regional (8 series) - lower-ranked metro winners play in
        // Stage 3: Sweet 16 (8 series) - top 8 metro winners + regional winners
        // Stage 4: QF, SF, Finals
        
        // Check all metro finals for completion
        const metroSeries = Object.keys(schedule.bySeries).filter(id => 
            id.startsWith('t3-metro-')
        );
        
        const metroResults = [];
        for (const seriesId of metroSeries) {
            const state = engines.PlayoffEngine.getSeriesState(schedule, seriesId);
            if (state.complete && state.winner) {
                metroResults.push({ winner: state.winner, loser: state.loser, seriesId });
            }
        }
        
        // Check if regional round is seeded
        const regionalSeries = Object.keys(schedule.bySeries).filter(id => 
            id.startsWith('t3-regional-')
        ).sort();
        
        const firstRegional = schedule.bySeries[regionalSeries[0]]?.[0];
        const regionalSeeded = firstRegional?.homeTeamId != null;
        
        // Seed regional round once all metro finals are complete
        if (metroResults.length === metroSeries.length && metroSeries.length > 0 && !regionalSeeded) {
            console.log(`📊 T3 Metro Finals complete: ${metroResults.length} winners`);
            
            // Sort metro winners by regular season record
            metroResults.sort((a, b) => (b.winner.wins - a.winner.wins) || (b.winner.pointDiff - a.winner.pointDiff));
            
            // Top 8 get byes to Sweet 16, teams 9-24 go to Regional round
            // Regional: 9v24, 10v23, 11v22, 12v21, 13v20, 14v19, 15v18, 16v17
            const byeTeams = metroResults.slice(0, 8).map(r => r.winner);
            const regionalTeams = metroResults.slice(8).map(r => r.winner);
            
            // Seed regional round (8 series)
            for (let i = 0; i < Math.min(8, regionalSeries.length, Math.floor(regionalTeams.length / 2)); i++) {
                const highSeed = regionalTeams[i];
                const lowSeed = regionalTeams[regionalTeams.length - 1 - i];
                if (highSeed && lowSeed && highSeed.id !== lowSeed.id) {
                    this._populateSeriesWithTeams(regionalSeries[i], highSeed, lowSeed);
                }
            }
            
            // Store bye teams for Sweet 16 seeding
            gameState._t3ByeTeams = byeTeams;
            
            // Update user's series ID if they're in the regional round or have a bye
            const userTeamId = gameState.userTeamId;
            if (userTeamId) {
                // Check if user has a bye (top 8)
                const userByeIdx = byeTeams.findIndex(t => t.id === userTeamId);
                if (userByeIdx >= 0) {
                    // User has a bye - they'll be seeded in Sweet 16 later
                    gameState._userHasT3Bye = true;
                    console.log(`🎯 User has T3 bye (seed ${userByeIdx + 1}), waiting for Sweet 16 seeding`);
                } else {
                    // Check if user is in regional round
                    for (let i = 0; i < regionalSeries.length; i++) {
                        const games = schedule.bySeries[regionalSeries[i]];
                        if (games?.[0] && (games[0].homeTeamId === userTeamId || games[0].awayTeamId === userTeamId)) {
                            gameState.userSeriesId = regionalSeries[i];
                            console.log(`🎯 User seeded in Regional: ${regionalSeries[i]}`);
                            break;
                        }
                    }
                }
            }
        }
        
        // Check if Sweet 16 needs seeding
        const sweet16Series = Object.keys(schedule.bySeries).filter(id => 
            id.startsWith('t3-sweet16-')
        ).sort();
        
        const firstSweet16 = schedule.bySeries[sweet16Series[0]]?.[0];
        const sweet16Seeded = firstSweet16?.homeTeamId != null;
        
        // Check regional completion
        const regionalResults = [];
        for (const seriesId of regionalSeries) {
            const state = engines.PlayoffEngine.getSeriesState(schedule, seriesId);
            if (state.complete && state.winner) {
                regionalResults.push(state.winner);
            }
        }
        
        // Seed Sweet 16 once all regionals complete
        if (regionalResults.length === regionalSeries.length && regionalSeries.length > 0 && !sweet16Seeded) {
            console.log(`📊 T3 Regional complete: ${regionalResults.length} winners`);
            
            const byeTeams = gameState._t3ByeTeams || [];
            // Sort regional winners by record
            regionalResults.sort((a, b) => (b.wins - a.wins) || (b.pointDiff - a.pointDiff));
            
            // Sweet 16: Bye team 1 vs Regional winner 8, etc.
            for (let i = 0; i < Math.min(8, sweet16Series.length); i++) {
                const byeTeam = byeTeams[i];
                const regionalWinner = regionalResults[regionalResults.length - 1 - i];
                if (byeTeam && regionalWinner) {
                    this._populateSeriesWithTeams(sweet16Series[i], byeTeam, regionalWinner);
                }
            }
            
            // Update user's series ID if they're in Sweet 16
            const userTeamId = gameState.userTeamId;
            if (userTeamId) {
                for (let i = 0; i < sweet16Series.length; i++) {
                    const games = schedule.bySeries[sweet16Series[i]];
                    if (games?.[0] && (games[0].homeTeamId === userTeamId || games[0].awayTeamId === userTeamId)) {
                        gameState.userSeriesId = sweet16Series[i];
                        gameState._userHasT3Bye = false;
                        console.log(`🎯 User seeded in Sweet 16: ${sweet16Series[i]}`);
                        break;
                    }
                }
            }
        }
        
        // Sweet 16 → QF advancement (handled by _getNextSeriesId)
        // QF → SF advancement (handled by _getNextSeriesId)
        // SF → Finals advancement (handled by _getNextSeriesId)
    }
    
    /**
     * Check if semi-final losers need to go to 3rd place game.
     */
    _checkThirdPlaceGames() {
        const { gameState, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        
        // T2 3rd place
        const t2Sf1 = engines.PlayoffEngine.getSeriesState(schedule, 't2-nat-sf-1');
        const t2Sf2 = engines.PlayoffEngine.getSeriesState(schedule, 't2-nat-sf-2');
        if (t2Sf1.complete && t2Sf2.complete && t2Sf1.loser && t2Sf2.loser) {
            const thirdPlace = schedule.bySeries['t2-3rd-place'];
            if (thirdPlace && thirdPlace[0] && !thirdPlace[0].homeTeamId) {
                this._populateSeriesWithTeams('t2-3rd-place', t2Sf1.loser, t2Sf2.loser);
            }
        }
        
        // T3 3rd place
        const t3Sf1 = engines.PlayoffEngine.getSeriesState(schedule, 't3-sf-1');
        const t3Sf2 = engines.PlayoffEngine.getSeriesState(schedule, 't3-sf-2');
        if (t3Sf1.complete && t3Sf2.complete && t3Sf1.loser && t3Sf2.loser) {
            const thirdPlace = schedule.bySeries['t3-3rd-place'];
            if (thirdPlace && thirdPlace[0] && !thirdPlace[0].homeTeamId) {
                this._populateSeriesWithTeams('t3-3rd-place', t3Sf1.loser, t3Sf2.loser);
            }
        }
    }
    
    /**
     * Populate a series with both teams (for known matchups).
     */
    _populateSeriesWithTeams(seriesId, higherSeed, lowerSeed) {
        const { gameState } = this.ctx;
        const schedule = gameState.playoffSchedule;
        const games = schedule.bySeries[seriesId];
        
        if (!games || !games.length) return;
        
        // Determine home court pattern based on bestOf
        const bestOf = games[0].bestOf || 7;
        const homePattern = bestOf === 7
            ? [higherSeed, higherSeed, lowerSeed, lowerSeed, higherSeed, lowerSeed, higherSeed]
            : bestOf === 5
            ? [higherSeed, higherSeed, lowerSeed, lowerSeed, higherSeed]
            : [higherSeed, lowerSeed, higherSeed];
        
        for (let i = 0; i < games.length; i++) {
            const game = games[i];
            const home = homePattern[i] || higherSeed;
            const away = home.id === higherSeed.id ? lowerSeed : higherSeed;
            
            game.higherSeedId = higherSeed.id;
            game.lowerSeedId = lowerSeed.id;
            game.homeTeamId = home.id;
            game.awayTeamId = away.id;
            game.homeTeam = home;
            game.awayTeam = away;
            game.placeholder = false;
        }
        
        console.log(`📋 Populated ${seriesId}: ${higherSeed.name} vs ${lowerSeed.name}`);
    }

    /**
     * Determine which series the winner advances to based on bracket logic.
     */
    _getNextSeriesId(completedSeriesId) {
        // Parse the series ID to understand the bracket position
        // Format: t{tier}-{round}-{conf}-{matchup} or t{tier}-{stage}-{matchup}
        const parts = completedSeriesId.split('-');
        const tier = parts[0]; // t1, t2, t3
        
        if (tier === 't1') {
            // T1: R1 → R2 → CF → Finals
            if (parts[1] === 'r1') {
                const conf = parts[2]; // east or west
                const matchup = parts[3]; // e.g., "1v8"
                // R1 winners: 1v8 & 4v5 → R2-1, 2v7 & 3v6 → R2-2
                const matchupNum = parseInt(matchup.split('v')[0]);
                const r2Num = (matchupNum === 1 || matchupNum === 4) ? 1 : 2;
                return `t1-r2-${conf}-${r2Num}`;
            }
            if (parts[1] === 'r2') {
                const conf = parts[2];
                return `t1-cf-${conf}`;
            }
            if (parts[1] === 'cf') {
                return 't1-finals';
            }
        }
        
        if (tier === 't2') {
            // T2: DivSemi → DivFinal → NatRound1 → NatQuarter → NatSemi → Finals
            // Series IDs: t2-div-{division-with-hyphens}-s1/s2/final
            // e.g., t2-div-great-lakes-s1 → parts = ['t2', 'div', 'great', 'lakes', 's1']
            
            if (parts[1] === 'div') {
                const suffix = parts[parts.length - 1]; // Last element: s1, s2, or final
                const divIdParts = parts.slice(2, -1); // Everything between 'div' and suffix
                const divId = divIdParts.join('-');
                
                if (suffix === 's1' || suffix === 's2') {
                    return `t2-div-${divId}-final`;
                }
                if (suffix === 'final') {
                    // Division final winners go to national tournament
                    // This is handled specially in _checkT2NationalTournamentSeeding
                    return null;
                }
            }
            
            // National tournament progression
            // t2-nat-r1-{n} → t2-nat-qf-{n/2}
            if (parts[1] === 'nat' && parts[2] === 'r1') {
                const matchNum = parseInt(parts[3]);
                const qfNum = Math.ceil(matchNum / 2);
                return `t2-nat-qf-${qfNum}`;
            }
            // t2-nat-qf-{n} → t2-nat-sf-{n/2}
            if (parts[1] === 'nat' && parts[2] === 'qf') {
                const matchNum = parseInt(parts[3]);
                const sfNum = Math.ceil(matchNum / 2);
                return `t2-nat-sf-${sfNum}`;
            }
            // t2-nat-sf-{n} → t2-finals
            if (parts[1] === 'nat' && parts[2] === 'sf') {
                return 't2-finals';
            }
        }
        
        if (tier === 't3') {
            // T3: MetroFinal → Regional → Sweet16 → Quarters → Semis → Finals
            // t3-metro-{metro}-final → t3-regional-{region}-{slot}
            if (parts[1] === 'metro') {
                // Metro finals winners go to regional, but we handle seeding specially
                return null;
            }
            // t3-regional-{region}-{n} → t3-sweet16-{n}
            if (parts[1] === 'regional') {
                // Regional winners advance to Sweet 16
                return null; // Handle seeding specially
            }
            // t3-sweet16-{n} → t3-qf-{n/2}
            if (parts[1] === 'sweet16') {
                const matchNum = parseInt(parts[2]);
                const qfNum = Math.ceil(matchNum / 2);
                return `t3-qf-${qfNum}`;
            }
            // t3-qf-{n} → t3-sf-{n/2}
            if (parts[1] === 'qf') {
                const matchNum = parseInt(parts[2]);
                const sfNum = Math.ceil(matchNum / 2);
                return `t3-sf-${sfNum}`;
            }
            // t3-sf-{n} → t3-finals (losers go to 3rd place)
            if (parts[1] === 'sf') {
                return 't3-finals';
            }
        }
        
        return null;
    }

    /**
     * Populate a placeholder series with a team from a completed series.
     */
    _populateSeriesWithTeam(seriesId, team, fromSeriesId) {
        const { gameState } = this.ctx;
        const schedule = gameState.playoffSchedule;
        const games = schedule.bySeries[seriesId];
        
        if (!games || !games.length) return;
        if (!team) return;
        
        // Determine seeding position based on fromSeriesId
        // In T1: 1v8 winner is higher seed than 4v5 winner in R2
        // In T2: s1 winner (1v4) is higher seed than s2 winner (2v3) in final
        const isHigherSeed = this._isHigherSeedAdvancement(fromSeriesId, seriesId);
        
        for (const game of games) {
            // Check if this team is already in the series
            if (game.higherSeedId === team.id || game.lowerSeedId === team.id) {
                return; // Already populated
            }
            
            if (isHigherSeed && !game.higherSeedId) {
                game.higherSeedId = team.id;
                // Don't set home/away yet - wait until both teams are known
            } else if (!isHigherSeed && !game.lowerSeedId) {
                game.lowerSeedId = team.id;
            } else if (!game.higherSeedId) {
                // Fallback: fill whichever slot is empty
                game.higherSeedId = team.id;
            } else if (!game.lowerSeedId) {
                game.lowerSeedId = team.id;
            }
            
            // If both teams are now set, finalize the home/away pattern
            if (game.higherSeedId && game.lowerSeedId) {
                this._finalizeSeriesMatchup(seriesId);
                return;
            }
        }
    }
    
    /**
     * Determine if a team advancing from a series should be the higher seed in the next round.
     */
    _isHigherSeedAdvancement(fromSeriesId, toSeriesId) {
        if (!fromSeriesId) return true; // Default to higher
        
        const parts = fromSeriesId.split('-');
        const tier = parts[0];
        
        if (tier === 't1') {
            // T1 R1: 1v8 and 2v7 winners are higher seeds in R2
            if (parts[1] === 'r1') {
                const matchup = parts[3];
                const seedNum = parseInt(matchup.split('v')[0]);
                return seedNum <= 2; // 1-seed or 2-seed winner is higher
            }
            // T1 R2: Series 1 winner is higher seed in CF
            if (parts[1] === 'r2') {
                return parts[3] === '1';
            }
            // T1 CF: East winner is higher seed in Finals (by convention)
            if (parts[1] === 'cf') {
                return parts[2] === 'east';
            }
        }
        
        if (tier === 't2') {
            // T2 Division: s1 (1v4) winner is higher seed than s2 (2v3) winner
            // Handle multi-word division names: t2-div-great-lakes-s1
            if (parts[1] === 'div') {
                const suffix = parts[parts.length - 1];
                if (suffix === 's1') return true;
                if (suffix === 's2') return false;
            }
            // T2 National: lower numbered series winner is higher seed
            if (parts[1] === 'nat') {
                const matchNum = parseInt(parts[3]);
                return matchNum % 2 === 1; // Odd series (1,3,5,7) winners are higher seeds
            }
        }
        
        if (tier === 't3') {
            // T3: lower numbered series winner is higher seed
            if (parts[1] === 'sweet16' || parts[1] === 'qf' || parts[1] === 'sf') {
                const matchNum = parseInt(parts[2]);
                return matchNum % 2 === 1; // Odd series winners are higher seeds
            }
        }
        
        return true; // Default
    }
    
    /**
     * Finalize a series matchup once both teams are known.
     */
    _finalizeSeriesMatchup(seriesId) {
        const { gameState } = this.ctx;
        const schedule = gameState.playoffSchedule;
        const games = schedule.bySeries[seriesId];
        
        if (!games || !games.length) return;
        
        const firstGame = games[0];
        if (!firstGame.higherSeedId || !firstGame.lowerSeedId) return;
        
        // Find team objects
        const allTeams = [
            ...(gameState.tier1Teams || []),
            ...(gameState.tier2Teams || []),
            ...(gameState.tier3Teams || [])
        ];
        const higherSeed = allTeams.find(t => t.id === firstGame.higherSeedId);
        const lowerSeed = allTeams.find(t => t.id === firstGame.lowerSeedId);
        
        if (!higherSeed || !lowerSeed) return;
        
        // Set home court pattern based on bestOf
        const bestOf = firstGame.bestOf || 7;
        const homePattern = bestOf === 7
            ? [higherSeed, higherSeed, lowerSeed, lowerSeed, higherSeed, lowerSeed, higherSeed]
            : bestOf === 5
            ? [higherSeed, higherSeed, lowerSeed, lowerSeed, higherSeed]
            : [higherSeed, lowerSeed, higherSeed];
        
        for (let i = 0; i < games.length; i++) {
            const game = games[i];
            const home = homePattern[i] || higherSeed;
            const away = home.id === higherSeed.id ? lowerSeed : higherSeed;
            
            game.homeTeamId = home.id;
            game.awayTeamId = away.id;
            game.homeTeam = home;
            game.awayTeam = away;
            game.placeholder = false;
        }
        
        console.log(`📋 Finalized ${seriesId}: ${higherSeed.name} vs ${lowerSeed.name}`);
    }

    // ─── Helper: Get current playoff round ───────────────────────────────────────

    /**
     * Get current playoff round for a specific tier.
     */
    _getCurrentPlayoffRoundForTier(tier) {
        const { gameState, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        
        if (!schedule) return null;
        
        const tierPrefix = `t${tier}-`;
        
        // Round order varies by tier
        const roundOrders = {
            1: ['Round1', 'Round2', 'ConfFinals', 'Finals'],
            2: ['DivSemi', 'DivFinal', 'NatRound1', 'NatQuarter', 'NatSemi', 'ThirdPlace', 'Finals'],
            3: ['MetroFinal', 'Regional', 'Sweet16', 'Quarter', 'Semi', 'ThirdPlace', 'Finals']
        };
        
        const roundOrder = roundOrders[tier] || roundOrders[1];
        
        for (const round of roundOrder) {
            // Get games for this tier and round
            const roundGames = schedule.games.filter(g => 
                g.seriesId?.startsWith(tierPrefix) && g.round === round
            );
            if (roundGames.length === 0) continue;
            
            // Check if any series in this round is incomplete
            const seriesIds = [...new Set(roundGames.map(g => g.seriesId))];
            for (const seriesId of seriesIds) {
                const state = engines.PlayoffEngine.getSeriesState(schedule, seriesId);
                if (!state.complete) {
                    return round;
                }
            }
        }
        
        return null;
    }

    /**
     * Check if a specific round is complete for a specific tier.
     */
    _isRoundCompleteForTier(round, tier) {
        const { gameState, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        
        if (!schedule) return true;
        
        const tierPrefix = `t${tier}-`;
        const roundGames = schedule.games.filter(g => 
            g.seriesId?.startsWith(tierPrefix) && g.round === round
        );
        
        if (roundGames.length === 0) return true;
        
        const seriesIds = [...new Set(roundGames.map(g => g.seriesId))];
        
        for (const seriesId of seriesIds) {
            const state = engines.PlayoffEngine.getSeriesState(schedule, seriesId);
            if (!state.complete) return false;
        }
        
        return true;
    }

    // ─── Helper: Update user's series for next round ─────────────────────────────

    _updateUserSeriesForNextRound() {
        const { gameState, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        const userSeriesId = gameState.userSeriesId;
        
        if (!schedule || !userSeriesId) return;
        
        const state = engines.PlayoffEngine.getSeriesState(schedule, userSeriesId);
        
        if (state.complete) {
            if (state.winner?.id === gameState.userTeamId) {
                // User won - find their next series
                const nextSeriesId = this._getNextSeriesId(userSeriesId);
                if (nextSeriesId) {
                    gameState.userSeriesId = nextSeriesId;
                    console.log(`🎯 User advances to series: ${nextSeriesId}`);
                }
            } else {
                // User eliminated
                gameState.userSeriesId = null;
                gameState.userInPlayoffs = false;
                console.log('❌ User eliminated from playoffs');
            }
        }
    }

    // ─── Helper: Check if all playoffs are complete ──────────────────────────────

    _checkPlayoffsComplete() {
        const { gameState, helpers } = this.ctx;
        const playoffData = gameState.playoffData;
        
        if (!playoffData) return;
        
        // Check if all three tier brackets are complete
        const t1Complete = this._isTierPlayoffsComplete(1);
        const t2Complete = this._isTierPlayoffsComplete(2);
        const t3Complete = this._isTierPlayoffsComplete(3);
        
        if (t1Complete && t2Complete && t3Complete) {
            console.log('🏆 All playoffs complete!');
            playoffData.completed = true;
            
            // Build postseason results for offseason flow
            this._buildPostseasonResults();
            
            helpers.saveGameState();
            
            // The PlayoffHub's onComplete callback will be triggered by user action
        }
    }

    _isTierPlayoffsComplete(tier) {
        const { gameState, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        
        if (!schedule) return false;
        
        // Find the finals series for this tier
        const finalsId = `t${tier}-finals`;
        const finalsGames = schedule.bySeries[finalsId];
        
        if (!finalsGames || finalsGames.length === 0) {
            // No finals series yet - check if we have any games at all for this tier
            const tierGames = schedule.games.filter(g => g.tier === tier);
            if (tierGames.length === 0) return true; // No games = complete (shouldn't happen)
            return false;
        }
        
        const state = engines.PlayoffEngine.getSeriesState(schedule, finalsId);
        return state.complete;
    }

    // ─── Helper: Build postseasonResults for offseason compatibility ─────────────

    _buildPostseasonResults() {
        const { gameState, engines } = this.ctx;
        const schedule = gameState.playoffSchedule;
        const playoffData = gameState.playoffData;
        
        if (!schedule || !playoffData) return;
        
        // Get champions from finals series
        const getChampion = (tier) => {
            const finalsId = `t${tier}-finals`;
            const state = engines.PlayoffEngine.getSeriesState(schedule, finalsId);
            return state.complete ? state.winner : null;
        };
        
        const getRunnerUp = (tier) => {
            const finalsId = `t${tier}-finals`;
            const state = engines.PlayoffEngine.getSeriesState(schedule, finalsId);
            return state.complete ? state.loser : null;
        };
        
        const getThirdPlace = (tier) => {
            const thirdId = `t${tier}-3rd-place`;
            const state = engines.PlayoffEngine.getSeriesState(schedule, thirdId);
            return state.complete ? state.winner : null;
        };
        
        const getThirdPlaceLoser = (tier) => {
            const thirdId = `t${tier}-3rd-place`;
            const state = engines.PlayoffEngine.getSeriesState(schedule, thirdId);
            return state.complete ? state.loser : null;
        };
        
        const t1Champion = getChampion(1);
        const t2Champion = getChampion(2);
        const t3Champion = getChampion(3);
        
        // Build basic results structure
        const results = {
            t1: {
                champion: t1Champion,
                runnerUp: getRunnerUp(1),
                completed: !!t1Champion
            },
            t2: {
                champion: t2Champion,
                runnerUp: getRunnerUp(2),
                thirdPlaceWinner: getThirdPlace(2),
                thirdPlaceLoser: getThirdPlaceLoser(2),
                completed: !!t2Champion
            },
            t3: {
                champion: t3Champion,
                runnerUp: getRunnerUp(3),
                thirdPlaceWinner: getThirdPlace(3),
                thirdPlaceLoser: getThirdPlaceLoser(3),
                completed: !!t3Champion
            },
            promoted: { toT1: [], toT2: [] },
            relegated: { fromT1: [], fromT2: [] }
        };
        
        // Calculate promotion (T2 → T1)
        // T2 promotion: champion, runner-up, 3rd place winner (or best record if not in top 3)
        if (t2Champion) {
            const t2Sorted = [...gameState.tier2Teams].sort((a, b) => {
                if (b.wins !== a.wins) return b.wins - a.wins;
                return b.pointDiff - a.pointDiff;
            });
            const bestRecord = t2Sorted[0];
            
            const promoted = [];
            // Best regular season record always promoted
            promoted.push(bestRecord);
            
            // Champion if different from best record
            if (t2Champion.id !== bestRecord.id) {
                promoted.push(t2Champion);
            }
            
            // Fill remaining from playoff finishers
            const finishOrder = [
                t2Champion,
                results.t2.runnerUp,
                results.t2.thirdPlaceWinner,
                results.t2.thirdPlaceLoser
            ].filter(t => t != null);
            
            for (const team of finishOrder) {
                if (promoted.length >= 3) break;
                if (!promoted.find(p => p.id === team.id)) {
                    promoted.push(team);
                }
            }
            
            // Fallback to regular season if needed
            while (promoted.length < 3) {
                for (const team of t2Sorted) {
                    if (!promoted.find(p => p.id === team.id)) {
                        promoted.push(team);
                        break;
                    }
                }
            }
            
            results.promoted.toT1 = promoted;
        }
        
        // Calculate promotion (T3 → T2)
        // T3 promotion: champion, runner-up, 3rd place winner
        if (t3Champion) {
            const promoted = [];
            if (t3Champion) promoted.push(t3Champion);
            if (results.t3.runnerUp) promoted.push(results.t3.runnerUp);
            if (results.t3.thirdPlaceWinner) promoted.push(results.t3.thirdPlaceWinner);
            results.promoted.toT2 = promoted;
        }
        
        // Calculate relegation (T1 → T2)
        // Bottom 3 teams by regular season record
        if (gameState.tier1Teams) {
            const t1Sorted = [...gameState.tier1Teams].sort((a, b) => {
                if (a.wins !== b.wins) return a.wins - b.wins; // Worst first
                return a.pointDiff - b.pointDiff;
            });
            results.relegated.fromT1 = t1Sorted.slice(0, 3);
        }
        
        // Calculate relegation (T2 → T3)
        // Bottom 3 teams by regular season record
        if (gameState.tier2Teams) {
            const t2Sorted = [...gameState.tier2Teams].sort((a, b) => {
                if (a.wins !== b.wins) return a.wins - b.wins; // Worst first
                return a.pointDiff - b.pointDiff;
            });
            results.relegated.fromT2 = t2Sorted.slice(0, 3);
        }
        
        gameState.postseasonResults = results;
        
        console.log('📊 Built postseasonResults:', {
            t1Champion: t1Champion?.name,
            t2Champion: t2Champion?.name,
            t3Champion: t3Champion?.name,
            promotedToT1: results.promoted.toT1.map(t => t.name),
            promotedToT2: results.promoted.toT2.map(t => t.name),
            relegatedFromT1: results.relegated.fromT1.map(t => t.name),
            relegatedFromT2: results.relegated.fromT2.map(t => t.name)
        });
    }
}
